name: Daily Send Report

on:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC = 03:00 Asia/Riyadh
  workflow_dispatch:       # زر تشغيل يدوي

concurrency:
  group: daily-send-report
  cancel-in-progress: false

jobs:
  send-report:
    runs-on: ubuntu-latest
    env:
      FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
      SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY }}

    steps:
      - name: Invoke Supabase Edge Function (Scheduled via Authorization)
        run: |
          set -eo pipefail

          URL_CLEAN="$(printf %s "$FUNCTION_URL" | tr -dc '[:print:]')"
          SR_KEY_CLEAN="$(printf %s "$SERVICE_ROLE_KEY" | tr -dc '[:print:]')"

          if [ -z "$URL_CLEAN" ]; then
            echo "ERROR: FUNCTION_URL is empty"; exit 1
          fi
          if [ -z "$SR_KEY_CLEAN" ]; then
            echo "ERROR: SERVICE_ROLE_KEY is empty"; exit 1
          fi

          http_code=$(curl -sS -o /tmp/resp.txt -w "%{http_code}" -X POST "$URL_CLEAN" \
            -H "Authorization: Bearer $SR_KEY_CLEAN" \
            -H "x-schedule: 1" \
            -H "Content-Type: application/json" \
            --data '{}')

          echo "HTTP $http_code"
          echo "--- Response ---"
          cat /tmp/resp.txt || true
          echo "----------------"

          if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 400 ]; then
            exit 1
          fi
