      - name: Call Supabase Edge Function (debug & sanitize)
        env:
          FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
          CRON_KEY: ${{ secrets.CRON_KEY }}
        run: |
          set -euo pipefail
          # نظّف القيم من أي مسافات/أسطر/CR
          URL_CLEAN="$(printf '%s' "$FUNCTION_URL" | tr -d '\r' | xargs)"
          KEY_CLEAN="$(printf '%s' "$CRON_KEY" | tr -d '\r' | xargs)"

          echo "Checking inputs..."
          if [ -z "$URL_CLEAN" ]; then
            echo "FUNCTION_URL is EMPTY"; exit 1
          fi
          if [ -z "$KEY_CLEAN" ]; then
            echo "CRON_KEY is EMPTY"; exit 1
          fi
          case "$URL_CLEAN" in
            https://*) : ;;
            *) echo "FUNCTION_URL must start with https:// — got: $URL_CLEAN"; exit 1 ;;
          esac

          echo "POST (masked) URL length: $(echo -n "$URL_CLEAN" | wc -c)"

          # النداء الفعلي مع لوج تفصيلي
          http_code=$(curl -sS -v -o /tmp/resp.txt -w "%{http_code}" -X POST "$URL_CLEAN" \
            -H "x-cron-key: $KEY_CLEAN" \
            -H "Content-Type: application/json" \
            --data '{}')

          echo "---- HTTP $http_code ----"
          echo "---- BODY ----"
          cat /tmp/resp.txt || true
          echo "-------------"

          [ "$http_code" -ge 400 ] && exit 1 || exit 0
