name: Daily Send Report

on:
  # تشغيل مجدول: كل يوم الساعة 03:00 فجراً بتوقيت الرياض
  schedule:
    - cron: '0 0 * * *'
  # تفعيل زر التشغيل اليدوي في صفحة Actions
  workflow_dispatch:

jobs:
  call-function:name: Send Daily Report

# This workflow runs daily at midnight UTC (03:00 KSA) and
# invokes the Supabase Edge Function to send the dname: Send Daily Report

# This workflow runs daily at midnight UTC (03:00 KSA) and
# invokes the Supabase Edge Function to send the daily email report.
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Edge Function
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            https://sygnesgnnaoadhrzacmp.functions.supabase.co/send-daily-reportaily email report.
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Edge Function
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            https://sygnesgnnaoadhrzacmp.functions.supabase.co/send-daily-report
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        env:
          FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
          CRON_KEY: ${{ secrets.CRON_KEY }}
        run: |
          set -eo pipefail
          URL_CLEAN="$(printf %s "$FUNCTION_URL" | tr -dc '[:print:]')"
          KEY_CLEAN="$(printf %s "$CRON_KEY" | tr -dc '[:print:]')"

          if [ -z "$URL_CLEAN" ]; then
            echo "ERROR: FUNCTION_URL is EMPTY"; exit 1
          fi
          if [ -z "$KEY_CLEAN" ]; then
            echo "ERROR: CRON_KEY is EMPTY"; exit 1
          fi

          # إرسال الطلب إلى الفانكشن
          http_code=$(curl -sS -o /tmp/resp.txt -w "%{http_code}" -X POST "$URL_CLEAN" \
            -H "x-cron-key: $KEY_CLEAN" \
            -H "Content-Type: application/json" \
            --data '{}')

          echo "HTTP $http_code"
          cat /tmp/resp.txt || true

          if [ "$http_code" -ge 400 ]; then
            exit 1
          fi
